services:
  - type: web
    name: mosquitoscope
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: FORCE_CPU
        value: "1"
      - key: TORCH_NUM_THREADS
        value: "1"
      - key: LOW_MEMORY
        value: "1"
      - key: DISABLE_TTA
        value: "1"
      - key: MAX_UPLOAD_MB
        value: "8"
      - key: HF_MODEL_REPO
        value: Sahil35077/mosquitoscope-convnextv2-tiny
    buildFilter:
      paths:
        - webapp/**
